### ISSUE TITLE
how to make it work with UPDD v 5.0?

### ISSUE THREAD

**Issue by sonvirgo** [kprinssu/VoodooI2C-client#2]
Works with UPDD v 6.0 FTSC1000
how to make it work with UPDD v 5.0?$ make
g++ VoodooI2CClient.cc updd.cc mouse.cc -o voodooi2c-client -std=c++11 -ldl "/usr/local/lib/libACE.dylib" -framework CoreGraphics -framework CoreFoundation
Undefined symbols for architecture x86_64:
  "_TBApiClose", referenced from:
      updd_stop() in updd-b98926.o
  "_TBApiGetRelativeDevice", referenced from:
      normalised_inject_touch(int, int, int, int, int, bool) in updd-b98926.o
  "_TBApiInjectTouch", referenced from:
      normalised_inject_touch(int, int, int, int, int, bool) in updd-b98926.o
  "_TBApiOpen", referenced from:
      updd_start() in updd-b98926.o
  "_TBApiRegisterEvent", referenced from:
      updd_start() in updd-b98926.o
  "_TBApiUnregisterEvent", referenced from:
      updd_stop() in updd-b98926.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [voodooi2c-client] Error 1
